### ISSUE TITLE
Problèmes de chronologie.

### ISSUE THREAD

**Issue by Cemoixerestre** [Mbodin/murder-generator#1]
J'ai fait plusieurs simulations. J'ai remarqué quelques bizzareries dans la chronologie.

À chaque fois que l'évènement « … est né·e » arrive, il est placé à la fin de la chronologie, c'est-à-dire que chaque personnage est né après avoir effectué un certains nombre d'actions dans sa vie. Est-ce une incohérence ? Ou est-ce que ça fait référence à autre chose ?

Une autre chose, dans une simulation, j'ai un évènement « Bob va souvent faire ses courses à la boutique de Alice » avant « Alice a toujours aimé le contact humain.
    Iel a donc naturellement décidé de devenir commerçant. ». Ne faudrait-il pas que l'évènement « Alice a décidé de devenir commerçant·e » soit placé avant ?

**Comment by Mbodin** [comment]
Merci pour le rapport de bug !
Tout à fait, c’est un bug. Malheureusement, je ne sais pas où il se trouve.
Dans les fichiers de données, il est clair que l’événement de naissance doit être avant tout autre événement personel du joueur (voir cette ligne : https://github.com/Mbodin/murder-generator/blob/master/data/identity.murder#L32), et de même pour l’événement des courses (ici : https://github.com/Mbodin/murder-generator/blob/master/data/job.murder#L80). Il faut que j’enquête.

Ce qui m’étonne, c’est que certaines dépendances sont bien prises en compte : si on demande à générer un fichier Graphviz pour les événements, une grande partie des contraintes est bien inférée, mais il en reste toujours quelques unes. C’est bizarre.

**Comment by Mbodin** [comment]
Alors, j’ai du nouveau ☺

Déjà, il y avait deux parties dans ce bug :
* la génération des contraintes entre les événements
* la résolution de ces contraintes.

Le bug le plus visible était dans la résolution (ce que je n’avais pas vu jusque là) : lors de mon tri topologique des événements, je construis une liste à l’envers pour des raisons techniques. Du coup je dois retourner cette liste après coup… sauf que je le faisais deux fois. Oups. Du coup la naissance se retrouvait de manière assez systématique à la fin de la chronologie. Cette partie du bug est maintenant réglée ☺

Il reste l’autre partie : la génération des contraintes (le plus simple pour le visualiser est de générer un fichier GraphViz pour les événements). Il y a deux types de contraintes : les contraintes universelles (« assume no event… ») et les contraintes existentielles (« assume event… »). J’ai mis pas mal d’effort dans la partie universelle, et je crois que ça fonctionne plutôt bien en ce moment ☺ Par contre la partie existentielle est assez bancale, et il arrive encore fréquement que des événements se retrouvent isolés alors qu’ils ne devraient pas. C’est le cas de la phrase sur le commerce que tu as mentionné. Bon, je vais enquêter.

En passant, est-ce que tu génères les scénarios sur l’interface en ligne ou l’interface en console ? L’interface en ligne est assez lente : n’hésites pas à tenter de compiler le projet pour l’avoir en local — c’est ce que je fais et c’est vachement plus rapide ! ☺

**Comment by Cemoixerestre** [comment]
Pour l'instant j'ai tout testé en ligne.
Merci pour tes conseils, je vais télécharger l'interface ce week-end.

**Comment by Cemoixerestre** [comment]
Ah, et j'ai oublié de me présenter, j'ai répondu à ton mail, je suis Alban.

**Comment by Mbodin** [comment]
J’ai l’impression que c’est mieux, non ? Je n’ai plus vu d’événement isolé depuis longtemps dans mes générations.
C’est assez étrange, parce qu’il ne me semblait pas avoir touché à une partie sensible de la partie du programme qui gère ça. Peut-être que parce que j’ai ajouté beaucoup d’événements dans les données, ça a rendu le bug moins fréquent (et ça a rendu le générateur très lent au passage… c’est un petit peu embêtant, mais c’est un autre problème).

Une autre hypothèse serait que les événements que l’on voyait trainer avant était des événements aux contraintes non résolues. Je m’explique : lorsque le générateur considère un élément, il ne regarde pas si les prémisses de l’élément sont satisfaites, mais si les prémisses sont compatibles avec l’événement courant. Le générateur essaye ensuite de trouver des éléments qui rempliront ces prémisses. Dans un état donné, il est donc possible d’avoir des attributs et des contacts « en attente ». Lors de l’exportation, si un tel attribut ou contact est toujours en attente, il passe en mode finalisé : l’idée est qu’il y a un trou que l’on n’a pas réussi à remplir, et on laisse au MJ le soin de trouver une excuse pour cela. Ça a pour conséquence que certains événements peuvent se retrouver un petit peu perdus. Peut-être que maintenant qu’il y a plus d’éléments, le générateur a les moyens de remplir les trous sans trop de problème et que l’on ne voit plus ce genre d’événements incompatibles ? Je ne sais pas.

Dans tous les cas, je compte ajouter l’information qu’un attribute / contact était en attente dans le json : ça permettra de comprendre un petit peu mieux ce qu’il s’est passé. Je vais faire ça probablement en milieu de semaine.

Lorsque tu avais déclaré le bug, j’avais remarqué que c’était particulièrement souvent que l’événement des courses se retrouve isolé. Maintenant, cet événement est toujours généré, mais ses contraintes sont bien générées. Bon, difficile de dire pourquoi (j’ai changé pas mal de petites choses un petit peu partout : c’était peut-être un plus petit bug résolu qui s’est propagé ?). Je vais fermer le rapport de bug, mais si tu arrives à le reproduire, je veux bien voir le json généré ☺
