### ISSUE TITLE
Error generating scenario

### ISSUE THREAD

**Issue by stellaruniversex** [Mbodin/murder-generator#4]
Error details: Not_found ; c5d43cc521d4002731a4c6f465a56324ba3732e6 ; init, getting translation file (1037735932), Translations ready, ask_for_languages, getting data/elements/notary.murder (286577428), getting data/elements/curses.murder (611196585), getting data/elements/job.murder (957726932), getting data/elements/memories.murder (1072105445), getting data/elements/language.murder (613600663), getting data/elements/wars.murder (402720656), getting data/elements/politics.murder (103196177), getting data/elements/friends.murder (638538590), getting data/elements/wounds.murder (409285985), getting data/elements/relations.murder (723313835), getting data/elements/kids.murder (511417758), getting data/elements/objectives.murder (275325782), getting data/elements/family.murder (425762360), getting data/elements/dreams.murder (617913590), getting data/elements/romance.murder (174772925), getting data/elements/identity.murder (42553381), getting data/elements/places.murder (58556926), getting data/elements/religion.murder (760625062), getting data/elements/secrets.murder (911999652), getting data/names/scientists.names (621704303), getting data/names/en.names (127473196), getting data/names/frequent_us.names (1039328025), getting data/names/fiction.names (812543679), getting data/names/pt.names (253455065), getting data/names/fr.names (685880534), getting data/names/frequent_fr.names (268128933), getting data/names/eo.names (139233958), load_or_create, ask_for_basic, ask_for_categories, ask_for_player_constraints, switching from 0 players to 7

**Comment by Mbodin** [comment]
Thanks for the report!
I can reproduce it. I will be investigating ☺

**Comment by Mbodin** [comment]
The error happens at https://github.com/Mbodin/murder-generator/blob/master/src/main.ml#L640 with the constructor `Place`. This is unexpected: `Place` is not meant to be a constructor, but an object. Objects were the last kind that have been introduced: it is not that much a surprise that they would cause problem, but I did not expected this one.

**Comment by Mbodin** [comment]
I think that it is now fixed. Do not hesitate to reopen this bug if you think otherwise ☺
